name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1-5'

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-jammy
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      URL: ${{ secrets.URL }}  
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        shell: bash
        run: |
          excluded_dates=("2025-04-10" "2025-04-18" "2025-04-21" "2025-04-22" "2025-04-23" "2025-04-24" "2025-04-25" "2025-05-01" "2025-05-02")
          today=$(date -u +'%Y-%m-%d')
          for date in "${excluded_dates[@]}"; do
            if [ "$today" == "$date" ]; then
              echo "should_skip=true" >> $GITHUB_OUTPUT
              echo "Skipping workflow on excluded date: $today"
              exit 0
            fi
          done
          echo "should_skip=false" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}

      - uses: actions/setup-node@v4
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        with:
          node-version: lts/*

      - name: Install dependencies
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        run: npm ci

      - name: Install Playwright Browsers
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
