name: Playwright Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1-5'

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-jammy
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      URL: ${{ secrets.URL }}  
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        shell: bash
        run: |
          # Define excluded date ranges
          excluded_ranges=(
            "2025-08-11:2025-08-15"
            "2025-08-25:2025-08-29"
          )
          today=$(date -u +'%Y-%m-%d')

          for range in "${excluded_ranges[@]}"; do
            start=$(echo "$range" | cut -d':' -f1)
            end=$(echo "$range" | cut -d':' -f2)
            if [[ "$today" >="$start" && "$today" <= "$end" ]]; then
              echo "should_skip=true" >> $GITHUB_OUTPUT
              echo "Skipping workflow on excluded date: $today"
              exit 0
            fi
          done

          echo "should_skip=false" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}

      - uses: actions/setup-node@v4
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        with:
          node-version: lts/*

      - name: Install dependencies
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        run: npm ci

      - name: Install Playwright Browsers
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
