name: Playwright Tests
on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * 1-5'  # Runs at 07:00 UTC Monday–Friday

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.1-jammy
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      URL: ${{ secrets.URL }}
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        shell: bash
        run: |
          # --- CONFIGURAZIONE ---
          # Fuso orario per la valutazione della data odierna (usa 'UTC' o 'Europe/Rome')
          TZ_VAL='UTC'

          # Date singole da escludere (YYYY-MM-DD)
          excluded_dates=(
            "2025-09-18"
          )

          # Range di date da escludere (YYYY-MM-DD:YYYY-MM-DD) - ESTREMI INCLUSI
          excluded_ranges=(
            "2025-10-20:2025-10-31"
          )
          # Per escludere solo l'interno del range, togli gli uguali nel test e lascia solo:  "$today" > "$start" && "$today" < "$end"

          # --- LOGICA ---
          today=$(TZ="$TZ_VAL" date +'%Y-%m-%d')

          # Esclusione date singole
          for d in "${excluded_dates[@]}"; do
            if [[ "$today" == "$d" ]]; then
              echo "should_skip=true" >> "$GITHUB_OUTPUT"
              echo "Skipping workflow on excluded single date: $today"
              exit 0
            fi
          done

          # Esclusione range (estremi inclusi)
          for range in "${excluded_ranges[@]}"; do
            start=${range%%:*}
            end=${range##*:}
            if [[ "$today" == "$start" || "$today" == "$end" || ( "$today" > "$start" && "$today" < "$end" ) ]]; then
              echo "should_skip=true" >> "$GITHUB_OUTPUT"
              echo "Skipping workflow on excluded range ($start..$end): $today"
              exit 0
            fi
          done

          echo "should_skip=false" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}

      - uses: actions/setup-node@v4
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        with:
          node-version: lts/*

      - name: Install dependencies
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        run: npm ci

      - name: Install Playwright Browsers
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        run: npx playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ steps.skip_check.outputs.should_skip != 'true' }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
