name: Playwright Tests
on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # This example triggers the workflow every day at 5:30 and 17:30 UTC
    # https://crontab.cronhub.io/
    - cron: '0 9 * * 1-5'
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    container:      
      ## build and test must run on the same os to share cache
      image: mcr.microsoft.com/playwright:v1.49.1-jammy
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      URL: ${{ secrets.URL }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
